Implement storing of IP parameters between runs
OSAL functions to save and load binary blobs

Add function to get MAC address from config

Handle IP address not set

Improve logging of IP addresses

Rename variables to better reflect their usage

Change revision prefix in sample application

Closes #92

diff --git a/src/osal/linux/set_network_parameters b/src/osal/linux/set_network_parameters
--- a/src/osal/linux/set_network_parameters
+++ b/src/osal/linux/set_network_parameters
@@ -32,14 +32,22 @@ DEFAULT_GATEWAY=$4
 HOSTNAME=$5
 SET_VALUES_PERMANENTLY=$6
 
-echo "Network script for ${INTERFACE}: " \
-   "Set IP ${IP_ADDRESS}, " \
-   "Netmask ${NETMASK}, " \
-   "Gateway ${DEFAULT_GATEWAY}. " \
-   "Permanent: ${SET_VALUES_PERMANENTLY}. " \
-   "Hostname: ${HOSTNAME}"
+# From a Profinet point of view there is no need to change the
+# host name of the Linux machine. The p-net stack will use the
+# name as station name internally.
+SKIP_SETTING_HOSTNAME=true
 
-# TODO The changes are not yet permanent.
+echo "Network script for ${INTERFACE}: " \
+   "Set IP ${IP_ADDRESS}  " \
+   "Netmask ${NETMASK}  " \
+   "Gateway ${DEFAULT_GATEWAY}  " \
+   "Permanent: ${SET_VALUES_PERMANENTLY}  " \
+   "Hostname: ${HOSTNAME}  " \
+   "Skip setting hostname: ${SKIP_SETTING_HOSTNAME}"
+
+# There is no need to set the changes permanently,
+# as the p-net stack will set the IP parameters on each start.
+# You are however free to use it if you like.
 
 if ! ip address flush label $INTERFACE; then
    echo "Failed to flush network interface"
@@ -65,15 +73,17 @@ else
    echo "No valid default gateway given. Skipping setting default gateway."
 fi
 
-if ! hostname $HOSTNAME; then
-   echo "Failed to set hostname to $HOSTNAME"
-   hostname_len=${#HOSTNAME}
-   if [ $hostname_len -gt 64 ]; then
-      echo "The given hostname length is ${hostname_len} characters." \
-      "Many Linux systems have a limit of 64 characters. The p-net stack uses" \
-      "a longer stationname internally."
+if [ "$SKIP_SETTING_HOSTNAME" = false ]; then
+   if ! hostname $HOSTNAME; then
+      echo "Failed to set hostname to $HOSTNAME"
+      hostname_len=${#HOSTNAME}
+      if [ $hostname_len -gt 64 ]; then
+         echo "The given hostname length is ${hostname_len} characters." \
+         "Many Linux systems have a limit of 64 characters. The p-net stack uses" \
+         "a longer stationname internally."
+      fi
+      exit 1
    fi
-   exit 1
 fi
 
 exit 0
