Release session after implicit read, and implement ping
When doing a remote change of IP-address or name, an implicit
read is first done by the IO-controller to read out info.
A session is created for this.
Close the session immediately after an implicit read,
as there is no info whether the session ever will be used again.

There might also be incoming RPC ping requests when changing
the IP-address. Implement ping reponse, and close the session if
the ping is received on a new session.

Improve logging and documentation.

Also the Linux script for changing the IP address etc should be
able to handle invalid (not set) default gatway.

Closes #54

diff --git a/src/osal/linux/set_network_parameters b/src/osal/linux/set_network_parameters
--- a/src/osal/linux/set_network_parameters
+++ b/src/osal/linux/set_network_parameters
@@ -56,9 +56,13 @@ if ! ip link set dev $INTERFACE up; then
    exit 1
 fi
 
-if ! ip route add default via $DEFAULT_GATEWAY; then
-   echo "Failed to set default gateway"
-   exit 1
+if [ "${DEFAULT_GATEWAY}" != "0.0.0.0" ]; then
+   if ! ip route add default via $DEFAULT_GATEWAY; then
+      echo "Failed to set default gateway"
+      exit 1
+   fi
+else
+   echo "No valid default gateway given. Skipping."
 fi
 
 if ! hostname $HOSTNAME; then
